secret:
  ignored_paths:
  - node_modules/
  - build/
  - '*.lock'
  - .env.example
  - env.example
  - '*.log'
  - coverage/
  - dist/
  - '**/*.example'
  - '**/*.sample'
  - scripts/
  ignored_detectors:
  - Generic High Entropy Secret
version: 2
